branches:
  only:
    - master
    - /.*travis.*/

env:
  secure: sfik69TnDpB69sxi82LNGTf+sO6J+9uogxpgJA8qt2jhYpJJ3WzOJd2qR+UKWk5Iavmv2W4LqqHCR5s6aQR7ERnLdCBXY6NGEsrZy91lZa+jSuPU/bP0NWPmEaym3z8WXHBkjIhiiCj/1lhar4q+lGVDBIhF+RhNzlesV590HtJ4H3KsNlNlvVrJurasrUy2OZ65Gm5vqRL3CmdzLuDmSUtNrDPWLb0ZX9Y5B9wQW3t+VLT8pHd9IE5VooL8twoBoVV406TV+2O15h7ahl/RSfYGdTXUyQRe55MFWlvJeanXkbElo7kEuMI8e0JwBdmNJ5ka7xha2STOTINc2kE8Qw==
  global:
    - secure: sfik69TnDpB69sxi82LNGTf+sO6J+9uogxpgJA8qt2jhYpJJ3WzOJd2qR+UKWk5Iavmv2W4LqqHCR5s6aQR7ERnLdCBXY6NGEsrZy91lZa+jSuPU/bP0NWPmEaym3z8WXHBkjIhiiCj/1lhar4q+lGVDBIhF+RhNzlesV590HtJ4H3KsNlNlvVrJurasrUy2OZ65Gm5vqRL3CmdzLuDmSUtNrDPWLb0ZX9Y5B9wQW3t+VLT8pHd9IE5VooL8twoBoVV406TV+2O15h7ahl/RSfYGdTXUyQRe55MFWlvJeanXkbElo7kEuMI8e0JwBdmNJ5ka7xha2STOTINc2kE8Qw==
  matrix:
    - secure: sfik69TnDpB69sxi82LNGTf+sO6J+9uogxpgJA8qt2jhYpJJ3WzOJd2qR+UKWk5Iavmv2W4LqqHCR5s6aQR7ERnLdCBXY6NGEsrZy91lZa+jSuPU/bP0NWPmEaym3z8WXHBkjIhiiCj/1lhar4q+lGVDBIhF+RhNzlesV590HtJ4H3KsNlNlvVrJurasrUy2OZ65Gm5vqRL3CmdzLuDmSUtNrDPWLb0ZX9Y5B9wQW3t+VLT8pHd9IE5VooL8twoBoVV406TV+2O15h7ahl/RSfYGdTXUyQRe55MFWlvJeanXkbElo7kEuMI8e0JwBdmNJ5ka7xha2STOTINc2kE8Qw==

language: java

jdk:
  - openjdk7
  - oraclejdk7

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report